// Plant database — 87 plants from CG Pruning Schedule
const PLANTS = [
  {
    "name": "Pittosporum",
    "size": "8–15′",
    "target": "-30–50%",
    "aggression": "Med–Heavy",
    "type": "Warm",
    "fertilize": "2–3 wks after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    }
  },
  {
    "name": "Ligustrum",
    "size": "10–20′",
    "target": "-40–60%",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "2–3 wks after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    }
  },
  {
    "name": "Podocarpus",
    "size": "10–20′",
    "target": "-30–50%",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "2–3 wks after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    }
  },
  {
    "name": "Westringia",
    "size": "4–8′",
    "target": "-25–40%",
    "aggression": "Medium",
    "type": "Year",
    "fertilize": "Light fert after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    }
  },
  {
    "name": "Roses",
    "size": "3–6′",
    "target": "-20–40%",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "After bloom (light)",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    }
  },
  {
    "name": "Salvia",
    "size": "2–5′",
    "target": "-20–40%",
    "aggression": "Light–Med",
    "type": "Year",
    "fertilize": "Light fert after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    }
  },
  {
    "name": "Muhlenbergia",
    "size": "2–4′",
    "target": "Cut to 2–6\"",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    }
  },
  {
    "name": "Lomandra",
    "size": "2–4′",
    "target": "Cut to 4–8\"",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Ceanothus",
    "size": "3–8′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Cool",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    }
  },
  {
    "name": "Muhlenbergia rigens (Deer Grass)",
    "size": "3–5′",
    "target": "Cut to 6–12\"",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "Spring fert",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "■"
    }
  },
  {
    "name": "Pennisetum setaceum (Fountain Grass)",
    "size": "3–4′",
    "target": "Cut to 4–6\"",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "Spring fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    }
  },
  {
    "name": "Nassella tenuissima (Mexican Feather Grass)",
    "size": "1–2′",
    "target": "Cut to 3–4\"",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    }
  },
  {
    "name": "Festuca glauca (Blue Fescue)",
    "size": "1–2′",
    "target": "Cut to 2–3\"",
    "aggression": "Medium",
    "type": "Cool",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    }
  },
  {
    "name": "Lomandra longifolia 'Breeze'",
    "size": "2–3′",
    "target": "Cut to 4–6\"",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Dietes iridioides (Fortnight Lily)",
    "size": "2–3′",
    "target": "Cut to 6\"",
    "aggression": "Medium",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "△",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    }
  },
  {
    "name": "Arctostaphylos 'Emerald Carpet'",
    "size": "1–2′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Cool",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    }
  },
  {
    "name": "Carex pensylvanica (PA Sedge)",
    "size": "1–2′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Shade",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "△",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    }
  },
  {
    "name": "Myoporum parvifolium",
    "size": "6–12\"",
    "target": "Cut to 2–4\"",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Senecio mandraliscae (Blue Senecio)",
    "size": "1–2′",
    "target": "Cut to 2–4\"",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "△",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    }
  },
  {
    "name": "Drosanthemum hispidum",
    "size": "4–8\"",
    "target": "Cut to 2–3\"",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "△",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    }
  },
  {
    "name": "Erigeron karvinskianus (Santa Barbara Daisy)",
    "size": "1–2′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    }
  },
  {
    "name": "Gazania rigens",
    "size": "6–12\"",
    "target": "Cut to 4–6\"",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "△",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    }
  },
  {
    "name": "Lantana camera (Lantana)",
    "size": "3–5′",
    "target": "-30–50%",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "Spring fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "△",
      "nov": "",
      "dec": ""
    }
  },
  {
    "name": "Salvia leucantha (Mexican Bush Sage)",
    "size": "3–4′",
    "target": "Cut to 6–12\"",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "△",
      "nov": "△",
      "dec": "△"
    }
  },
  {
    "name": "Nepeta 'Walker's Low'",
    "size": "2–3′",
    "target": "Cut to 4–6\"",
    "aggression": "Medium",
    "type": "Year",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "△",
      "oct": "",
      "nov": "",
      "dec": ""
    }
  },
  {
    "name": "Lavandula angustifolia 'Hidcote' (Lavender)",
    "size": "2–3′",
    "target": "Cut to 6–8\"",
    "aggression": "Medium",
    "type": "Cool",
    "fertilize": "Light after bloom",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "■"
    }
  },
  {
    "name": "Heuchera maxima (Coral Bells)",
    "size": "1–2′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Shade",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "△",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    }
  },
  {
    "name": "Rosa hybrids (Shrub Roses)",
    "size": "3–5′",
    "target": "-20–40%",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "After bloom",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    }
  },
  {
    "name": "Olea europaea 'Little Ollie'",
    "size": "6–8′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "△",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Trachelospermum jasminoides (Star Jasmine)",
    "size": "10–15′",
    "target": "-20–30%",
    "aggression": "Light–Med",
    "type": "Year",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "△",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    }
  },
  {
    "name": "Viburnum davidii",
    "size": "3–4′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "△",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    }
  },
  {
    "name": "Photinia × fraseri (Fraser Photinia)",
    "size": "8–15′",
    "target": "-30–40%",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Spring fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "■"
    }
  },
  {
    "name": "Buxus 'Green Beauty'",
    "size": "3–5′",
    "target": "-20–30%",
    "aggression": "Light–Med",
    "type": "Year",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    }
  },
  {
    "name": "Heteromeles arbutifolia (Toyon)",
    "size": "8–15′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    }
  },
  {
    "name": "Quercus agrifolia (Coast Live Oak)",
    "size": "15–30′",
    "target": "",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    }
  },
  {
    "name": "Arbutus 'Marina' (Marina Strawberry Tree)",
    "size": "15–30′",
    "target": "",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    }
  },
  {
    "name": "Prunus ilicifolia ssp. lyonii (Catalina Cherry)",
    "size": "",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Chilopsis linearis (Desert Willow)",
    "size": "15–30′",
    "target": "",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    }
  },
  {
    "name": "x Chitalpa tashkentensis 'Pink Dawn' (Pink Chitalpa)",
    "size": "15–30′",
    "target": "",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    }
  },
  {
    "name": "Cercis occidentalis (Western Redbud)",
    "size": "",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Aesculus californica (California Buckeye)",
    "size": "15–30′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Year",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    }
  },
  {
    "name": "Juglans californica var. californica (Southern California Black Walnut)",
    "size": "15–30′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Year",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    }
  },
  {
    "name": "Artemisia californica (California Sagebrush)",
    "size": "3–8′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Artemisia californica 'Canyon Gray' (Canyon Gray Sagebrush)",
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Artemisia californica 'Montara' (Montara Sagebrush)",
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Rhus ovata (Sugar Bush)",
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Rhus integrifolia (Lemonade Berry)",
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Prunus ilicifolia ssp. ilicifolia (Hollyleaf Cherry)",
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Rhamnus californica (Coffeeberry)",
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Calliandra californica (Baja Fairy Duster)",
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Isomeris arborea (Bladderpod)",
    "size": "3–8′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Eriogonum fasciculatum (California Buckwheat)",
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Eriogonum cinereum (Ashyleaf Buckwheat)",
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Eriogonum arborescens (Santa Cruz Island Buckwheat)",
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Eriogonum fasciculatum 'Theodore Payne' (Theodore Payne Buckwheat)",
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Baccharis pilularis 'Pigeon Point' (Pigeon Point Coyote Brush)",
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Lepechinia fragrans (Fragrant Pitcher Sage)",
    "size": "3–8′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Abutilon palmeri (Palmer's Indian Mallow)",
    "size": "3–8′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Sphaeralcea ambigua (Desert Mallow / Apricot Mallow)",
    "size": "1–3′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Eriogonum grande var. rubescens (Red Buckwheat)",
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Achillea millefolium (Common Yarrow)",
    "size": "1–3′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Asclepias fascicularis (Narrow Leaf Milkweed)",
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Asclepias speciosa (Showy Milkweed)",
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Anemopsis californica (Yerba Mansa)",
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Iris douglasiana (Douglas Iris)",
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Bouteloua gracilis (Blue Grama)",
    "size": "2–4′",
    "target": "",
    "aggression": "Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    }
  },
  {
    "name": "Leymus condensatus 'Canyon Prince' (Canyon Prince Wild Rye)",
    "size": "2–4′",
    "target": "",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    }
  },
  {
    "name": "Carex tumulicola (Foothill Sedge / Berkeley Sedge)",
    "size": "",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Carex pansa (Sand Dune Sedge)",
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Carex barbarae (Valley Sedge)",
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Sesleria autumnalis (Sesleria Autumnalis)",
    "size": "2–4′",
    "target": "",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    }
  },
  {
    "name": "Berberis aquifolium var. repens (Creeping Barberry / Creeping Oregon Grape)",
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Erigeron glaucus (Seaside Daisy)",
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Hesperaloe parviflora (Red Yucca)",
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Agave attenuata 'Boutin Blue' (Blue Fox Tail Agave)",
    "size": "1–4′",
    "target": "",
    "aggression": "Light",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": ""
    }
  },
  {
    "name": "Agave attenuata (Fox Tail Agave)",
    "size": "1–4′",
    "target": "",
    "aggression": "Light",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": ""
    }
  },
  {
    "name": "Agave 'Blue Flame' (Blue Flame Agave)",
    "size": "1–4′",
    "target": "",
    "aggression": "Light",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": ""
    }
  },
  {
    "name": "Aloe vera (Aloe Vera)",
    "size": "1–4′",
    "target": "",
    "aggression": "Light",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": ""
    }
  },
  {
    "name": "Aloe 'Blue Elf' (Blue Elf Aloe)",
    "size": "1–4′",
    "target": "",
    "aggression": "Light",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": ""
    }
  },
  {
    "name": "Rosmarinus officinalis (Rosemary)",
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Bougainvillea spectabilis (Bougainvillea)",
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Olea europaea (Olive Tree)",
    "size": "15–30′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Year",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    }
  },
  {
    "name": "Cupressus sempervirens (Italian Cypress)",
    "size": "15–30′",
    "target": "",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    }
  },
  {
    "name": "Juniperus chinensis 'Torulosa' (Juniper)",
    "size": "",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Rhaphiolepis indica (Indian Hawthorn)",
    "size": "3–8′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Carissa macrocarpa (Natal Plum)",
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "name": "Phormium tenax (New Zealand Flax)",
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  }
];
// Export for module use
if (typeof module !== "undefined" && module.exports) module.exports = PLANTS;
