// Plant database — 152 plants from CG Pruning Schedule
const PLANTS = [
  {
    "botanical": "Pittosporum",
    "common": "Pittosporum",
    "synonyms": [
      "pitt",
      "pittosporum"
    ],
    "size": "8–15′",
    "target": "-30–50%",
    "aggression": "Med–Heavy",
    "type": "Warm",
    "fertilize": "2–3 wks after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Ligustrum",
    "common": "Privet",
    "synonyms": [
      "privet",
      "wax privet"
    ],
    "size": "10–20′",
    "target": "-40–60%",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "2–3 wks after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Podocarpus",
    "common": "Podocarpus",
    "synonyms": [
      "podocarpus"
    ],
    "size": "10–20′",
    "target": "-30–50%",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "2–3 wks after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Westringia",
    "common": "Coast Rosemary",
    "synonyms": [
      "westringia",
      "rosemary",
      "coast rosemary"
    ],
    "size": "4–8′",
    "target": "-25–40%",
    "aggression": "Medium",
    "type": "Year",
    "fertilize": "Light fert after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": [
      "assets/plants/westringia_gray_box_1.jpg",
      "assets/plants/westringia_gray_box_2.jpg",
      "assets/plants/westringia_gray_box_3.jpg",
      "assets/plants/westringia_fruticosa_mundi_1.jpg",
      "assets/plants/westringia_fruticosa_mundi_2.jpg",
      "assets/plants/westringia_fruticosa_mundi_3.jpg",
      "assets/plants/westringia_aussie_box_1.jpg",
      "assets/plants/westringia_aussie_box_2.jpg",
      "assets/plants/westringia_aussie_box_3.jpg",
      "assets/plants/westringia_fruticosa_morning_light_1.jpg",
      "assets/plants/westringia_fruticosa_morning_light_2.jpg",
      "assets/plants/westringia_fruticosa_morning_light_3.jpg"
    ]
  },
  {
    "botanical": "Roses",
    "common": "Rose",
    "synonyms": [
      "rose",
      "roses",
      "hybrid rose"
    ],
    "size": "3–6′",
    "target": "-20–40%",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "After bloom (light)",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": [
      "assets/plants/roses_2.jpg",
      "assets/plants/rosa_iceberg.jpg"
    ]
  },
  {
    "botanical": "Salvia",
    "common": "Sage",
    "synonyms": [
      "salvia",
      "sage"
    ],
    "size": "2–5′",
    "target": "-20–40%",
    "aggression": "Light–Med",
    "type": "Year",
    "fertilize": "Light fert after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Muhlenbergia capillaris",
    "common": "Pink Muhly Grass",
    "synonyms": [
      "muhly",
      "muhlenbergia"
    ],
    "size": "2–4′",
    "target": "Cut to 2–6\"",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    },
    "images": [
      "assets/plants/muhlenbergia_capillaris.jpg",
      "assets/plants/muhlenbergia_capillaris2.jpg",
      "assets/plants/muhlenbergia_capillaris3.jpg"
    ]
  },
  {
    "botanical": "Lomandra",
    "common": "Mat Rush",
    "synonyms": [
      "lomandra",
      "mat rush"
    ],
    "size": "2–4′",
    "target": "Cut to 4–8\"",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Ceanothus",
    "common": "California Lilac",
    "synonyms": [
      "ceanothus",
      "california lilac",
      "wild lilac"
    ],
    "size": "3–8′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Cool",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Muhlenbergia rigens",
    "common": "Deer Grass",
    "synonyms": [],
    "size": "3–5′",
    "target": "Cut to 6–12\"",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "Spring fert",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "■"
    },
    "images": [
      "assets/plants/muhlenbergia_rigens.jpg"
    ]
  },
  {
    "botanical": "Pennisetum setaceum",
    "common": "Fountain Grass",
    "synonyms": [],
    "size": "3–4′",
    "target": "Cut to 4–6\"",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "Spring fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    },
    "images": [
      "assets/plants/pennisetum_setaceum_7.jpg",
      "assets/plants/pennisetum_setaceum2.jpg",
      "assets/plants/pennisetum_setaceum3.jpg"
    ]
  },
  {
    "botanical": "Nassella tenuissima",
    "common": "Mexican Feather Grass",
    "synonyms": [],
    "size": "1–2′",
    "target": "Cut to 3–4\"",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    },
    "images": [
      "assets/plants/stipa_nassella_tenuissima.jpg"
    ]
  },
  {
    "botanical": "Festuca glauca",
    "common": "Blue Fescue",
    "synonyms": [],
    "size": "1–2′",
    "target": "Cut to 2–3\"",
    "aggression": "Medium",
    "type": "Cool",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Lomandra longifolia 'Breeze'",
    "common": "Breeze Mat Rush",
    "synonyms": [
      "lomandra breeze",
      "breeze"
    ],
    "size": "2–3′",
    "target": "Cut to 4–6\"",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/lomandra_longifolia_breeze_1.jpg",
      "assets/plants/lomandra_longifolia_breeze_2.jpg",
      "assets/plants/lomandra_longifolia_breeze_3.jpg"
    ]
  },
  {
    "botanical": "Dietes iridioides",
    "common": "Fortnight Lily",
    "synonyms": [],
    "size": "2–3′",
    "target": "Cut to 6\"",
    "aggression": "Medium",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "△",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Arctostaphylos 'Emerald Carpet'",
    "common": "Emerald Carpet Manzanita",
    "synonyms": [
      "emerald carpet",
      "manzanita"
    ],
    "size": "1–2′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Cool",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Carex pensylvanica",
    "common": "PA Sedge",
    "synonyms": [],
    "size": "1–2′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Shade",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "△",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Myoporum parvifolium",
    "common": "Myoporum",
    "synonyms": [
      "myoporum",
      "prostrate myoporum"
    ],
    "size": "6–12\"",
    "target": "Cut to 2–4\"",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Senecio mandraliscae",
    "common": "Blue Senecio",
    "synonyms": [],
    "size": "1–2′",
    "target": "Cut to 2–4\"",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "△",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Drosanthemum hispidum",
    "common": "Drosanthemum",
    "synonyms": [
      "drosanthemum",
      "rose carpet"
    ],
    "size": "4–8\"",
    "target": "Cut to 2–3\"",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "△",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Erigeron karvinskianus",
    "common": "Santa Barbara Daisy",
    "synonyms": [],
    "size": "1–2′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Gazania rigens",
    "common": "Gazania",
    "synonyms": [
      "gazania",
      "treasure flower"
    ],
    "size": "6–12\"",
    "target": "Cut to 4–6\"",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "△",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Salvia leucantha",
    "common": "Mexican Bush Sage",
    "synonyms": [],
    "size": "3–4′",
    "target": "Cut to 6–12\"",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "△",
      "nov": "△",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Nepeta 'Walker's Low'",
    "common": "Walker's Low Catmint",
    "synonyms": [
      "walkers low",
      "catmint",
      "catnip"
    ],
    "size": "2–3′",
    "target": "Cut to 4–6\"",
    "aggression": "Medium",
    "type": "Year",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "△",
      "oct": "",
      "nov": "",
      "dec": ""
    },
    "images": []
  },
  {
    "botanical": "Lavandula angustifolia 'Hidcote'",
    "common": "Lavender",
    "synonyms": [],
    "size": "2–3′",
    "target": "Cut to 6–8\"",
    "aggression": "Medium",
    "type": "Cool",
    "fertilize": "Light after bloom",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Heuchera maxima",
    "common": "Coral Bells",
    "synonyms": [],
    "size": "1–2′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Shade",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "△",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Rosa hybrids",
    "common": "Shrub Roses",
    "synonyms": [],
    "size": "3–5′",
    "target": "-20–40%",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "After bloom",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Olea europaea 'Little Ollie'",
    "common": "Little Ollie Olive",
    "synonyms": [
      "little ollie",
      "dwarf olive"
    ],
    "size": "6–8′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "△",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Trachelospermum jasminoides",
    "common": "Star Jasmine",
    "synonyms": [],
    "size": "10–15′",
    "target": "-20–30%",
    "aggression": "Light–Med",
    "type": "Year",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "△",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": [
      "assets/plants/trachelospermum_jasminoides.jpg",
      "assets/plants/trachelospermum_jasminoides2.jpg",
      "assets/plants/trachelospermum_jasminoides3.jpg",
      "assets/plants/trachelospermum_jasminoides_1.jpg",
      "assets/plants/trachelospermum_jasminoides_2.jpg",
      "assets/plants/trachelospermum_jasminoides_3.jpg",
      "assets/plants/trachelospermum_jasminoides_4.jpg",
      "assets/plants/trachelospermum_jasminoides_5.jpg",
      "assets/plants/trachelospermum_jasminoides_6.jpg"
    ]
  },
  {
    "botanical": "Viburnum davidii",
    "common": "David Viburnum",
    "synonyms": [
      "david viburnum",
      "viburnum"
    ],
    "size": "3–4′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "△",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Photinia × fraseri",
    "common": "Fraser Photinia",
    "synonyms": [],
    "size": "8–15′",
    "target": "-30–40%",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Spring fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Buxus 'Green Beauty'",
    "common": "Green Beauty Boxwood",
    "synonyms": [
      "green beauty boxwood",
      "boxwood"
    ],
    "size": "3–5′",
    "target": "-20–30%",
    "aggression": "Light–Med",
    "type": "Year",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Heteromeles arbutifolia",
    "common": "Toyon",
    "synonyms": [],
    "size": "8–15′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Quercus agrifolia",
    "common": "Coast Live Oak",
    "synonyms": [],
    "size": "15–30′",
    "target": "",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Arbutus 'Marina'",
    "common": "Marina Strawberry Tree",
    "synonyms": [],
    "size": "15–30′",
    "target": "",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Prunus ilicifolia ssp. lyonii",
    "common": "Catalina Cherry",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Chilopsis linearis",
    "common": "Desert Willow",
    "synonyms": [],
    "size": "15–30′",
    "target": "",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "x Chitalpa tashkentensis 'Pink Dawn'",
    "common": "Pink Chitalpa",
    "synonyms": [],
    "size": "15–30′",
    "target": "",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Cercis occidentalis",
    "common": "Western Redbud",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Aesculus californica",
    "common": "California Buckeye",
    "synonyms": [],
    "size": "15–30′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Year",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Juglans californica var. californica",
    "common": "Southern California Black Walnut",
    "synonyms": [],
    "size": "15–30′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Year",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Artemisia californica",
    "common": "California Sagebrush",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Artemisia californica 'Canyon Gray'",
    "common": "Canyon Gray Sagebrush",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Artemisia californica 'Montara'",
    "common": "Montara Sagebrush",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Rhus ovata",
    "common": "Sugar Bush",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Rhus integrifolia",
    "common": "Lemonade Berry",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Prunus ilicifolia ssp. ilicifolia",
    "common": "Hollyleaf Cherry",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Rhamnus californica",
    "common": "Coffeeberry",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Calliandra californica",
    "common": "Baja Fairy Duster",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Isomeris arborea",
    "common": "Bladderpod",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Eriogonum fasciculatum",
    "common": "California Buckwheat",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Eriogonum cinereum",
    "common": "Ashyleaf Buckwheat",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Eriogonum arborescens",
    "common": "Santa Cruz Island Buckwheat",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Eriogonum fasciculatum 'Theodore Payne'",
    "common": "Theodore Payne Buckwheat",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Baccharis pilularis 'Pigeon Point'",
    "common": "Pigeon Point Coyote Brush",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Lepechinia fragrans",
    "common": "Fragrant Pitcher Sage",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Abutilon palmeri",
    "common": "Palmer's Indian Mallow",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Sphaeralcea ambigua",
    "common": "Desert Mallow / Apricot Mallow",
    "synonyms": [],
    "size": "1–3′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Eriogonum grande var. rubescens",
    "common": "Red Buckwheat",
    "synonyms": [],
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Achillea millefolium",
    "common": "Common Yarrow",
    "synonyms": [],
    "size": "1–3′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Asclepias fascicularis",
    "common": "Narrow Leaf Milkweed",
    "synonyms": [],
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Asclepias speciosa",
    "common": "Showy Milkweed",
    "synonyms": [],
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Anemopsis californica",
    "common": "Yerba Mansa",
    "synonyms": [],
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Iris douglasiana",
    "common": "Douglas Iris",
    "synonyms": [],
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Bouteloua gracilis",
    "common": "Blue Grama",
    "synonyms": [],
    "size": "2–4′",
    "target": "",
    "aggression": "Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    },
    "images": [
      "assets/plants/bouteloua_gracilis_blonde_ambition.jpg",
      "assets/plants/bouteloua_gracilis2.jpg",
      "assets/plants/bouteloua_gracilis3.jpg"
    ]
  },
  {
    "botanical": "Leymus condensatus 'Canyon Prince'",
    "common": "Canyon Prince Wild Rye",
    "synonyms": [],
    "size": "2–4′",
    "target": "",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Carex tumulicola",
    "common": "Foothill Sedge / Berkeley Sedge",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Carex pansa",
    "common": "Sand Dune Sedge",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Carex barbarae",
    "common": "Valley Sedge",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Sesleria autumnalis",
    "common": "Sesleria Autumnalis",
    "synonyms": [],
    "size": "2–4′",
    "target": "",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Berberis aquifolium var. repens",
    "common": "Creeping Barberry / Creeping Oregon Grape",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Erigeron glaucus",
    "common": "Seaside Daisy",
    "synonyms": [],
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Hesperaloe parviflora",
    "common": "Red Yucca",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Agave attenuata 'Boutin Blue'",
    "common": "Blue Fox Tail Agave",
    "synonyms": [],
    "size": "1–4′",
    "target": "",
    "aggression": "Light",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": ""
    },
    "images": []
  },
  {
    "botanical": "Agave attenuata",
    "common": "Fox Tail Agave",
    "synonyms": [],
    "size": "1–4′",
    "target": "",
    "aggression": "Light",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": ""
    },
    "images": []
  },
  {
    "botanical": "Agave 'Blue Flame'",
    "common": "Blue Flame Agave",
    "synonyms": [],
    "size": "1–4′",
    "target": "",
    "aggression": "Light",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": ""
    },
    "images": []
  },
  {
    "botanical": "Aloe vera",
    "common": "Aloe Vera",
    "synonyms": [],
    "size": "1–4′",
    "target": "",
    "aggression": "Light",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": ""
    },
    "images": []
  },
  {
    "botanical": "Aloe 'Blue Elf'",
    "common": "Blue Elf Aloe",
    "synonyms": [],
    "size": "1–4′",
    "target": "",
    "aggression": "Light",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": ""
    },
    "images": []
  },
  {
    "botanical": "Rosmarinus officinalis",
    "common": "Rosemary",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Bougainvillea spectabilis",
    "common": "Bougainvillea",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/bougainvillea_rosenka_pink_gold.jpg"
    ]
  },
  {
    "botanical": "Olea europaea",
    "common": "Olive Tree",
    "synonyms": [],
    "size": "15–30′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Year",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Cupressus sempervirens",
    "common": "Italian Cypress",
    "synonyms": [],
    "size": "15–30′",
    "target": "",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Juniperus chinensis 'Torulosa'",
    "common": "Juniper",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Rhaphiolepis indica",
    "common": "Indian Hawthorn",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Carissa macrocarpa",
    "common": "Natal Plum",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/carissa_macrocarpa_1.jpg",
      "assets/plants/carissa_macrocarpa_2.jpg",
      "assets/plants/carissa_macrocarpa_3.jpg"
    ]
  },
  {
    "botanical": "Carissa macrocarpa 'Green Carpet'",
    "common": "Green Carpet Natal Plum",
    "synonyms": [
      "carissa green carpet",
      "green carpet"
    ],
    "size": "1–2′",
    "target": "Light shape as needed",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/carissa_green_carpet_1.jpg",
      "assets/plants/carissa_green_carpet_2.jpg",
      "assets/plants/carissa_green_carpet_3.jpg"
    ]
  },
  {
    "botanical": "Phormium tenax",
    "common": "New Zealand Flax",
    "synonyms": [],
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Achillea millefolium 'Pomegranate'",
    "common": "Pomegranate Yarrow",
    "synonyms": [],
    "size": "2′",
    "target": "Cut to 6–8″",
    "aggression": "Medium",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/achillea_millefolium_pomegranate.jpg",
      "assets/plants/achillea_millefolium_pomegranate2.jpg",
      "assets/plants/achillea_millefolium_pomegranate3.jpg",
      "assets/plants/achillea_millefolium_pomegranate_1.jpg",
      "assets/plants/achillea_millefolium_pomegranate_2.jpg",
      "assets/plants/achillea_millefolium_pomegranate_3.jpg",
      "assets/plants/achillea_millefolium_pomegranate_4.jpg",
      "assets/plants/achillea_millefolium_pomegranate_5.jpg",
      "assets/plants/achillea_millefolium_pomegranate_6.jpg"
    ]
  },
  {
    "botanical": "Azalea 'Orange Delight'",
    "common": "Orange Delight Azalea",
    "synonyms": [],
    "size": "3–5′",
    "target": "Light shape after bloom",
    "aggression": "Light",
    "type": "Shade",
    "fertilize": "Acid fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/azalea_orange_delight.jpg",
      "assets/plants/azalea_orange_delight_2.jpg",
      "assets/plants/azalea_orange_delight_3.jpg",
      "assets/plants/azalea_orange_delight_1.jpg",
      "assets/plants/azalea_orange_delight_4.jpg",
      "assets/plants/azalea_orange_delight_5.jpg",
      "assets/plants/azalea_orange_delight_6.jpg",
      "assets/plants/azalea_orange_delight_7.jpg",
      "assets/plants/azalea_orange_delight_8.jpg"
    ]
  },
  {
    "botanical": "Hydrangea macrophylla 'Nikko Blue'",
    "common": "Nikko Blue Hydrangea",
    "synonyms": [],
    "size": "4–6′",
    "target": "Deadhead + light trim",
    "aggression": "Light",
    "type": "Shade",
    "fertilize": "Rich fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/hydrangea_macrophylla_nikko_blue_1.jpg",
      "assets/plants/hydrangea_macrophylla_nikko_blue_2.jpg",
      "assets/plants/hydrangea_macrophylla_nikko_blue_3.jpg",
      "assets/plants/hydrangea_macrophylla_nikko_blue_4.jpg",
      "assets/plants/hydrangea_macrophylla_nikko_blue_5.jpg",
      "assets/plants/hydrangea_macrophylla_nikko_blue_6.jpg"
    ]
  },
  {
    "botanical": "Hydrangea macrophylla 'Leuchtfeuer'",
    "common": "Leuchtfeuer Hydrangea",
    "synonyms": [],
    "size": "4–6′",
    "target": "Deadhead + light trim",
    "aggression": "Light",
    "type": "Shade",
    "fertilize": "Rich fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/hydrangea_macrophylla_leuchtfeuer_1.jpg",
      "assets/plants/hydrangea_macrophylla_leuchtfeuer_2.jpg",
      "assets/plants/hydrangea_macrophylla_leuchtfeuer_3.jpg",
      "assets/plants/hydrangea_macrophylla_leuchtfeuer_4.jpg",
      "assets/plants/hydrangea_macrophylla_leuchtfeuer_5.jpg",
      "assets/plants/hydrangea_macrophylla_leuchtfeuer_6.jpg"
    ]
  },
  {
    "botanical": "Xylosma congestum",
    "common": "Xylosma",
    "synonyms": [],
    "size": "8–15′",
    "target": "-20–40%",
    "aggression": "Medium",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/xylosma_congestum.jpg",
      "assets/plants/xylosma_congestum2.jpg",
      "assets/plants/xylosma_congestum3.jpg",
      "assets/plants/xylosma_congestum_1.jpg",
      "assets/plants/xylosma_congestum_2.jpg",
      "assets/plants/xylosma_congestum_3.jpg",
      "assets/plants/xylosma_congestum_4.jpg",
      "assets/plants/xylosma_congestum_5.jpg",
      "assets/plants/xylosma_congestum_6.jpg"
    ]
  },
  {
    "botanical": "Asparagus densiflorus 'Myers'",
    "common": "Myers Asparagus Fern",
    "synonyms": [],
    "size": "2–3′",
    "target": "Clean up dead fronds",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/asparagus_densiflorus_myers.jpg",
      "assets/plants/asparagus_densiflorus_myers_2.jpg",
      "assets/plants/asparagus_densiflorus_myers_3.jpg",
      "assets/plants/asparagus_densiflorus_myers_4.jpg",
      "assets/plants/asparagus_densiflorus_myers_1.jpg",
      "assets/plants/asparagus_densiflorus_myers_5.jpg",
      "assets/plants/asparagus_densiflorus_myers_6.jpg",
      "assets/plants/asparagus_densiflorus_myers_7.jpg",
      "assets/plants/asparagus_densiflorus_myers_8.jpg",
      "assets/plants/asparagus_densiflorus_myers_9.jpg"
    ]
  },
  {
    "botanical": "Philodendron 'Xanadu'",
    "common": "Xanadu Philodendron",
    "synonyms": [],
    "size": "3–5′",
    "target": "Remove damaged leaves",
    "aggression": "Light",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/philodendron_xanadu_1.jpg",
      "assets/plants/philodendron_xanadu_2.jpg",
      "assets/plants/philodendron_xanadu_3.jpg"
    ]
  },
  {
    "botanical": "Limonium perezii",
    "common": "Sea Lavender",
    "synonyms": [],
    "size": "2–3′",
    "target": "Cut back after bloom",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/limonium_perezii_1.jpg",
      "assets/plants/limonium_perezii_2.jpg",
      "assets/plants/limonium_perezii_3.jpg",
      "assets/plants/limonium_perezii_4.jpg",
      "assets/plants/limonium_perezii_5.jpg",
      "assets/plants/limonium_perezii_6.jpg"
    ]
  },
  {
    "botanical": "Dietes",
    "common": "Dietes",
    "synonyms": [],
    "size": "2–3′",
    "target": "Cut to 6–8″ annually",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/dietes_1.jpg",
      "assets/plants/dietes_2.jpg",
      "assets/plants/dietes_3.jpg",
      "assets/plants/dietes_4.jpg",
      "assets/plants/dietes_5.jpg",
      "assets/plants/dietes_6.jpg"
    ]
  },
  {
    "botanical": "Lavandula dentata",
    "common": "French Lavender",
    "synonyms": [],
    "size": "2–3′",
    "target": "Trim after bloom",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert after trim",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/lavandula_dentata_1.jpg",
      "assets/plants/lavandula_dentata_2.jpg",
      "assets/plants/lavandula_dentata_3.jpg",
      "assets/plants/lavandula_dentata_4.jpg",
      "assets/plants/lavandula_dentata_5.jpg",
      "assets/plants/lavandula_dentata_6.jpg"
    ]
  },
  {
    "botanical": "Lavandula x ginginsii 'Goodwin Creek Grey'",
    "common": "Goodwin Creek Grey Lavender",
    "synonyms": [],
    "size": "2–3′",
    "target": "Trim after bloom",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert after trim",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/lavandula_ginginsii_goodwin_creek_grey.jpg",
      "assets/plants/lavandula_ginginsii_goodwin_creek_grey2.jpg",
      "assets/plants/lavandula_ginginsii_goodwin_creek_grey3.jpg"
    ]
  },
  {
    "botanical": "Tulbaghia violacea",
    "common": "Society Garlic",
    "synonyms": [],
    "size": "1–2′",
    "target": "Cut back after bloom",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/tulbaghia_violacea_1.jpg",
      "assets/plants/tulbaghia_violacea_2.jpg",
      "assets/plants/tulbaghia_violacea_3.jpg"
    ]
  },
  {
    "botanical": "Phlomis fruticosa",
    "common": "Jerusalem Sage",
    "synonyms": [],
    "size": "3–4′",
    "target": "Cut back after bloom",
    "aggression": "Medium",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/phlomis_fruticosa_1.jpg",
      "assets/plants/phlomis_fruticosa_2.jpg",
      "assets/plants/phlomis_fruticosa_3.jpg"
    ]
  },
  {
    "botanical": "Achillea 'Moonshine' Yellow",
    "common": "Moonshine Yarrow",
    "synonyms": [],
    "size": "2′",
    "target": "Cut to 6–8″",
    "aggression": "Medium",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/achillea_moonshine_yellow.jpg",
      "assets/plants/achillea_moonshine_yellow2.jpg",
      "assets/plants/achillea_moonshine_yellow_1.jpg",
      "assets/plants/achillea_moonshine_yellow_2.jpg",
      "assets/plants/achillea_moonshine_yellow_3.jpg",
      "assets/plants/achillea_moonshine_yellow_4.jpg"
    ]
  },
  {
    "botanical": "Azalea 'Southern Charm' (Pink)",
    "common": "Southern Charm Azalea",
    "synonyms": [],
    "size": "4–6′",
    "target": "Light shape after bloom",
    "aggression": "Light",
    "type": "Shade",
    "fertilize": "Acid fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/azalea_southern_charm_pink.jpg",
      "assets/plants/azalea_southern_charm_pink2.jpg",
      "assets/plants/azalea_southern_charm_pink3.jpg"
    ]
  },
  {
    "botanical": "Azalea 'Red Bird'",
    "common": "Red Bird Azalea",
    "synonyms": [],
    "size": "3–4′",
    "target": "Light shape after bloom",
    "aggression": "Light",
    "type": "Shade",
    "fertilize": "Acid fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/azalea_red_bird.jpg",
      "assets/plants/azalea_red_bird_2.jpg",
      "assets/plants/azalea_red_bird_3.jpg",
      "assets/plants/azalea_red_bird_1.jpg",
      "assets/plants/azalea_red_bird_4.jpg",
      "assets/plants/azalea_red_bird_5.jpg",
      "assets/plants/azalea_red_bird_6.jpg",
      "assets/plants/azalea_red_bird_7.jpg",
      "assets/plants/azalea_red_bird_8.jpg"
    ]
  },
  {
    "botanical": "Lomandra longifolia 'Platinum Beauty'",
    "common": "Platinum Beauty Lomandra",
    "synonyms": [],
    "size": "3–4′",
    "target": "Cut to 4–6″ annually",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/lomandra_longifolia_platinum_beauty_1.jpg",
      "assets/plants/lomandra_longifolia_platinum_beauty_2.jpg",
      "assets/plants/lomandra_longifolia_platinum_beauty_3.jpg"
    ]
  },
  {
    "botanical": "Strelitzia nicolai",
    "common": "White Bird of Paradise",
    "synonyms": [],
    "size": "15–25′",
    "target": "Remove dead leaves",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/strelitzia_nocolao_00.jpg",
      "assets/plants/strelitzia_nocolao_01.jpg",
      "assets/plants/strelitzia_nocolao_02.jpg",
      "assets/plants/strelitzia_nocolao2.jpg",
      "assets/plants/strelitzia_nocolao3.jpg",
      "assets/plants/strelitzia_nicolai_1.jpg",
      "assets/plants/strelitzia_nicolai_2.jpg",
      "assets/plants/strelitzia_nicolai_3.jpg"
    ]
  },
  {
    "botanical": "Tecoma capensis",
    "common": "Cape Honeysuckle",
    "synonyms": [],
    "size": "6–10′",
    "target": "-30–50%",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": [
      "assets/plants/tecomaria_capensis_orange.jpg",
      "assets/plants/tecomaria_capensis_orange2.jpg",
      "assets/plants/tecomaria_capensis_orange3.jpg"
    ]
  },
  {
    "botanical": "Strelitzia reginae",
    "common": "Bird of Paradise",
    "synonyms": [],
    "size": "4–6′",
    "target": "Remove dead leaves/seed heads",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/strelitzia_regimae_00.jpg",
      "assets/plants/strelitzia_regimae_01.jpg",
      "assets/plants/strelitzia_regimae_02.jpg",
      "assets/plants/strelitzia_regimae_03.jpg",
      "assets/plants/strelitzia_regimae2.jpg",
      "assets/plants/strelitzia_regimae3.jpg",
      "assets/plants/strelitzia_reginae_1.jpg",
      "assets/plants/strelitzia_reginae_2.jpg",
      "assets/plants/strelitzia_reginae_3.jpg"
    ]
  },
  {
    "botanical": "Tecoma 'Orange Jubilee'",
    "common": "Orange Jubilee Tecoma",
    "synonyms": [],
    "size": "8–12′",
    "target": "-30–50%",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": [
      "assets/plants/tecomaria_orange_jubliee.jpg",
      "assets/plants/tecomaria_orange_jubliee_2.jpg",
      "assets/plants/tecomaria_orange_jubilee2.jpg",
      "assets/plants/tecomaria_orange_jubilee3.jpg"
    ]
  },
  {
    "botanical": "Tecoma stans",
    "common": "Yellow Bells",
    "synonyms": [
      "tacoma stans",
      "yellow bells",
      "yellow elder"
    ],
    "size": "6–12′",
    "target": "-30–50%",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": [
      "assets/plants/tecoma_stans_1.jpg",
      "assets/plants/tecoma_stans_2.jpg",
      "assets/plants/tecoma_stans_3.jpg"
    ]
  },
  {
    "botanical": "Salvia 'Allen Chickering'",
    "common": "Allen Chickering Salvia",
    "synonyms": [],
    "size": "3–4′",
    "target": "Cut back after bloom",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": [
      "assets/plants/salvia_allen_chickering_1.jpg",
      "assets/plants/salvia_allen_chickering_2.jpg",
      "assets/plants/salvia_allen_chickering_3.jpg"
    ]
  },
  {
    "botanical": "Salvia leucantha 'Santa Barbara'",
    "common": "Santa Barbara Mexican Sage",
    "synonyms": [],
    "size": "3–4′",
    "target": "Cut to 12–18″ in winter",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/salvia_leucantha_santa_barbara_1.jpg",
      "assets/plants/salvia_leucantha_santa_barbara_2.jpg",
      "assets/plants/salvia_leucantha_santa_barbara_3.jpg"
    ]
  },
  {
    "botanical": "Salvia leucantha 'Danielle's Dream'",
    "common": "Danielle's Dream Salvia",
    "synonyms": [],
    "size": "3–4′",
    "target": "Cut to 12–18″ in winter",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/salvia_leucantha_danielles_dream.jpg",
      "assets/plants/salvia_leucantha_danielles_dream2.jpg",
      "assets/plants/salvia_leucantha_danielles_dream3.jpg"
    ]
  },
  {
    "botanical": "Salvia 'Mystic Spires'",
    "common": "Mystic Spires Salvia",
    "synonyms": [],
    "size": "2–3′",
    "target": "Cut back after bloom",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": [
      "assets/plants/salvia_mystic_spires_1.jpg",
      "assets/plants/salvia_mystic_spires_2.jpg",
      "assets/plants/salvia_mystic_spires_3.jpg"
    ]
  },
  {
    "botanical": "Bougainvillea 'La Jolla'",
    "common": "La Jolla Bougainvillea",
    "synonyms": [],
    "size": "6–8′",
    "target": "Trim as needed",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": [
      "assets/plants/bougainvillea_la_jolla.jpg",
      "assets/plants/bougainvillea_la_jolla2.jpg",
      "assets/plants/bougainvillea_la_jolla3.jpg",
      "assets/plants/bougainvillea_la_jolla_1.jpg",
      "assets/plants/bougainvillea_la_jolla_2.jpg",
      "assets/plants/bougainvillea_la_jolla_3.jpg",
      "assets/plants/bougainvillea_la_jolla_4.jpg",
      "assets/plants/bougainvillea_la_jolla_5.jpg",
      "assets/plants/bougainvillea_la_jolla_6.jpg"
    ]
  },
  {
    "botanical": "Cordyline 'Lime Passion'",
    "common": "Lime Passion Cordyline",
    "synonyms": [],
    "size": "3–5′",
    "target": "Remove dead leaves",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/cordyline_lime_passion_1.jpg",
      "assets/plants/cordyline_lime_passion_2.jpg",
      "assets/plants/cordyline_lime_passion_3.jpg",
      "assets/plants/cordyline_lime_passion_4.jpg",
      "assets/plants/cordyline_lime_passion_5.jpg",
      "assets/plants/cordyline_lime_passion_6.jpg"
    ]
  },
  {
    "botanical": "Bougainvillea 'Barbara Karst'",
    "common": "Barbara Karst Bougainvillea",
    "synonyms": [],
    "size": "6–10′",
    "target": "Trim as needed",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": [
      "assets/plants/bougainvillea_barbara_karst.jpg",
      "assets/plants/bougainvillea_barbara_karst2.jpg",
      "assets/plants/bougainvillea_barbara_karst3.jpg",
      "assets/plants/bougainvillea_barbara_karst_1.jpg",
      "assets/plants/bougainvillea_barbara_karst_2.jpg",
      "assets/plants/bougainvillea_barbara_karst_3.jpg",
      "assets/plants/bougainvillea_barbara_karst_4.jpg",
      "assets/plants/bougainvillea_barbara_karst_5.jpg",
      "assets/plants/bougainvillea_barbara_karst_6.jpg"
    ]
  },
  {
    "botanical": "Leucadendron discolor 'pom pom'",
    "common": "Pom Pom Leucadendron",
    "synonyms": [],
    "size": "4–6′",
    "target": "Light shape after bloom",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "None or very light",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/leucadendron_discolor_pom_pom.jpg",
      "assets/plants/leucadendron_discolor_pom_pom2.jpg",
      "assets/plants/leucadendron_discolor_pom_pom3.jpg"
    ]
  },
  {
    "botanical": "Cordyline 'Design-a-line'",
    "common": "Design-a-Line Cordyline",
    "synonyms": [],
    "size": "3–4′",
    "target": "Remove dead leaves",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/cordyline_design_a_line_1.jpg",
      "assets/plants/cordyline_design_a_line_2.jpg",
      "assets/plants/cordyline_design_a_line_3.jpg",
      "assets/plants/cordyline_design_a_line_4.jpg",
      "assets/plants/cordyline_design_a_line_5.jpg",
      "assets/plants/cordyline_design_a_line_6.jpg",
      "assets/plants/cordyline_design_a_line_7.jpg"
    ]
  },
  {
    "botanical": "Dianella 'Tesmanica Variegata'",
    "common": "Variegated Flax Lily",
    "synonyms": [],
    "size": "2–3′",
    "target": "Cut to 6–8″ annually",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/dianella_tesmanica_variegata.jpg",
      "assets/plants/dianella_tesmanica_variegata2.jpg",
      "assets/plants/dianella_tesmanica_variegata3.jpg"
    ]
  },
  {
    "botanical": "Dianella revoluta 'Little Rev'",
    "common": "Little Rev Dianella",
    "synonyms": [],
    "size": "1–2′",
    "target": "Cut to 6–8″ annually",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/dianella_revoluta_little_rev_1.jpg",
      "assets/plants/dianella_revoluta_little_rev_2.jpg",
      "assets/plants/dianella_revoluta_little_rev_3.jpg",
      "assets/plants/dianella_revoluta_little_rev_4.jpg",
      "assets/plants/dianella_revoluta_little_rev_5.jpg",
      "assets/plants/dianella_revoluta_little_rev_6.jpg"
    ]
  },
  {
    "botanical": "Agapanthus 'Tinkerbell'",
    "common": "Tinkerbell Lily of the Nile",
    "synonyms": [],
    "size": "1–2′",
    "target": "Remove dead stalks after bloom",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/agapanthus_tinkerbell.jpg",
      "assets/plants/agapanthus_tinkerbell_2.jpg",
      "assets/plants/agapanthus_tinkerbell_3.jpg",
      "assets/plants/agapanthus_tinkerbell_1.jpg",
      "assets/plants/agapanthus_tinkerbell_4.jpg",
      "assets/plants/agapanthus_tinkerbell_5.jpg",
      "assets/plants/agapanthus_tinkerbell_6.jpg",
      "assets/plants/agapanthus_tinkerbell_7.jpg",
      "assets/plants/agapanthus_tinkerbell_8.jpg"
    ]
  },
  {
    "botanical": "Hemerocallis 'Stella d'Oro'",
    "common": "Stella de Oro Daylily",
    "synonyms": [],
    "size": "1–2′",
    "target": "Cut back in late winter",
    "aggression": "Medium",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/hemercocallis_stella_d_orro.jpg",
      "assets/plants/hemercocallis_stella_d_orro2.jpg",
      "assets/plants/hemercocallis_stella_d_orro3.jpg"
    ]
  },
  {
    "botanical": "Chondropetalum Tectorum",
    "common": "Cape Rush",
    "images": [
      "assets/plants/chondropetalum_tectorum_1.jpg",
      "assets/plants/chondropetalum_tectorum_2.jpg",
      "assets/plants/chondropetalum_tectorum_3.jpg"
    ],
    "size": "3–4′",
    "target": "Cut old stalks to ground annually",
    "aggression": "Light",
    "type": "Year-round",
    "fertilize": "Light feed in spring",
    "calendar": {
      "jan": "■",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "botanical": "Lantana \"Confetti\"",
    "common": "Confetti Lantana",
    "images": [
      "assets/plants/lanatana_confetti_00.jpg",
      "assets/plants/lanatana_confetti_01.jpg",
      "assets/plants/lanatana_confetti_02.jpg",
      "assets/plants/lanatana_confetti2.jpg",
      "assets/plants/lanatana_confetti3.jpg"
    ],
    "size": "3–4′",
    "target": "Hard cut to 12″ in late winter",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "Light fert after hard cut",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "",
      "dec": ""
    }
  },
  {
    "botanical": "Lantana \"New Gold\"",
    "common": "New Gold Lantana",
    "images": [
      "assets/plants/lanatana_new_gold_00.jpg",
      "assets/plants/lanatana_new_gold_01.jpg",
      "assets/plants/lanatana_new_gold_02.jpg",
      "assets/plants/lanatana_new_gold2.jpg",
      "assets/plants/lanatana_new_gold3.jpg"
    ],
    "size": "12–18″",
    "target": "Trim lightly to shape",
    "aggression": "Light",
    "type": "Warm",
    "fertilize": "Light feed in spring",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "",
      "nov": "",
      "dec": ""
    }
  },
  {
    "botanical": "Pennisetum 'Red Bunny'",
    "common": "Red Bunny Fountain Grass",
    "images": [
      "assets/plants/pennisetum_massalcum_red_bunny.jpg",
      "assets/plants/pennisetum_massalcum_red_bunny2.jpg",
      "assets/plants/pennisetum_massalcum_red_bunny3.jpg"
    ],
    "size": "2–3′",
    "target": "Cut to 6″ in late winter",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light feed in spring",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "",
      "nov": "",
      "dec": ""
    }
  },
  {
    "botanical": "Shefflera Arboricola",
    "common": "Arboricola",
    "images": [
      "assets/plants/shefflera_arboricola_00.jpg",
      "assets/plants/shefflera_arboricola_01.jpg",
      "assets/plants/shefflera_arboricola_02.jpg",
      "assets/plants/shefflera_arboricola2.jpg",
      "assets/plants/shefflera_arboricola3.jpg"
    ],
    "size": "6–8′",
    "target": "Light shaping cuts only",
    "aggression": "Light",
    "type": "Year-round",
    "fertilize": "Feed in spring",
    "calendar": {
      "jan": "■",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "botanical": "Lantana montevidensis",
    "common": "Purple Lantana",
    "images": [
      "assets/plants/lantana_montevidensis_1.jpg",
      "assets/plants/lantana_montevidensis_2.jpg",
      "assets/plants/lantana_montevidensis_3.jpg",
      "assets/plants/lantana_montevidensis_4.jpg",
      "assets/plants/lantana_montevidensis_5.jpg",
      "assets/plants/lantana_montevidensis_6.jpg"
    ],
    "size": "2–3′",
    "target": "Trim to shape in late winter",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light feed in spring",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "",
      "dec": ""
    }
  },
  {
    "botanical": "Bougainvillea 'Raspberry Ocean'",
    "common": "Raspberry Ocean Bougainvillea",
    "images": [
      "assets/plants/bougainvillea_rosenka_1.jpg",
      "assets/plants/bougainvillea_rosenka_2.jpg",
      "assets/plants/bougainvillea_rosenka_3.jpg"
    ],
    "size": "4–6′",
    "target": "Trim to shape, remove dead blooms",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light feed in spring",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "",
      "dec": ""
    }
  },
  {
    "botanical": "Bougainvillea 'Raspberry Ice'",
    "common": "Raspberry Ice Bougainvillea",
    "synonyms": [
      "bougainvillea raspberry ice",
      "raspberry ice"
    ],
    "size": "4–6'",
    "target": "Trim to shape, remove dead blooms",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light feed in spring",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "",
      "dec": ""
    },
    "images": [
      "assets/plants/bougainvillea_raspberry_ice_1.jpg",
      "assets/plants/bougainvillea_raspberry_ice_2.jpg",
      "assets/plants/bougainvillea_raspberry_ice_3.jpg"
    ]
  },
  {
    "botanical": "Bougainvillea 'Jamaica White'",
    "common": "Jamaica White Bougainvillea",
    "synonyms": [
      "bougainvillea jamaica white",
      "jamaica white"
    ],
    "size": "6–10′",
    "target": "Trim to shape, remove dead blooms",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light feed in spring",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "",
      "dec": ""
    },
    "images": [
      "assets/plants/bougainvillea_jamaica_white_1.jpg",
      "assets/plants/bougainvillea_jamaica_white_2.jpg",
      "assets/plants/bougainvillea_jamaica_white_3.jpg"
    ]
  },
  {
    "botanical": "Bougainvillea brasiliensis",
    "common": "Brazilian Bougainvillea",
    "synonyms": [
      "bougainvillea brasiliensis",
      "brasiliensis"
    ],
    "size": "10–20′",
    "target": "Trim to shape, remove dead blooms",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light feed in spring",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "",
      "dec": ""
    },
    "images": [
      "assets/plants/bougainvillea_brasiliensis_1.jpg",
      "assets/plants/bougainvillea_brasiliensis_2.jpg",
      "assets/plants/bougainvillea_brasiliensis_3.jpg"
    ]
  },
  {
    "botanical": "Cordyline australis \"Red Star\"",
    "common": "Red Star Cordyline",
    "images": [
      "assets/plants/cordyline_red_star.jpg",
      "assets/plants/cordyline_australis_red_star_2.jpg",
      "assets/plants/cordyline_australis_red_star_3.jpg"
    ],
    "size": "6–8′",
    "target": "Remove dead lower leaves",
    "aggression": "Light",
    "type": "Year-round",
    "fertilize": "Feed in spring",
    "calendar": {
      "jan": "■",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "botanical": "Helictotrichon sempervirens",
    "common": "Blue Oat Grass",
    "images": [
      "assets/plants/helictotrichon_sempervirens.jpg",
      "assets/plants/helictotrichon_sempervirens_2.jpg",
      "assets/plants/helictotrichon_sempervirens_3.jpg"
    ],
    "size": "2–3′",
    "target": "Cut to 6″ in late winter",
    "aggression": "Medium",
    "type": "Cool",
    "fertilize": "Light feed in spring",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "",
      "aug": "",
      "sep": "■",
      "oct": "■",
      "nov": "",
      "dec": ""
    }
  },
  {
    "botanical": "Melinis nerviglumis",
    "common": "Ruby Silk Grass",
    "images": [
      "assets/plants/melinis_nerviglumis.jpg",
      "assets/plants/melinis_nerviglumis2.jpg",
      "assets/plants/melinis_nerviglumis3.jpg"
    ],
    "size": "2–3′",
    "target": "Cut to 6″ in late winter",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light feed in spring",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "",
      "nov": "",
      "dec": ""
    }
  },
  {
    "botanical": "Miscanthus sinensis",
    "common": "Maiden Grass",
    "images": [
      "assets/plants/miscanthus_sinensis.jpg",
      "assets/plants/miscanthus_sinensis2.jpg",
      "assets/plants/miscanthus_sinensis3.jpg"
    ],
    "size": "5–7′",
    "target": "Cut to 12″ in late winter",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light feed in spring",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "",
      "dec": ""
    }
  },
  {
    "botanical": "Miscanthus sinensis 'Morning Light'",
    "common": "Morning Light Maiden Grass",
    "images": [
      "assets/plants/miscanthus_sinensis_morning_light.jpg",
      "assets/plants/miscanthus_sinensis_morning_light2.jpg",
      "assets/plants/miscanthus_sinensis_morning_light3.jpg"
    ],
    "size": "4–6′",
    "target": "Cut to 12″ in late winter",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light feed in spring",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "",
      "dec": ""
    }
  },
  {
    "botanical": "Pennisetum Fairy Tails",
    "common": "Fairy Tails Fountain Grass",
    "images": [
      "assets/plants/pennisetum_fairy_tails.jpg",
      "assets/plants/pennisetum_fairy_tails_2.jpg",
      "assets/plants/pennisetum_fairy_tails_3.jpg"
    ],
    "size": "3–4′",
    "target": "Cut to 6″ in late winter",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light feed in spring",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "",
      "nov": "",
      "dec": ""
    }
  },
  {
    "botanical": "Pennisetum spathiolatum",
    "common": "Slender Fountain Grass",
    "images": [
      "assets/plants/pennisetum_spathiolatum.jpg",
      "assets/plants/pennisetum_spathiolatum_2.jpg",
      "assets/plants/pennisetum_spathiolatum3.jpg"
    ],
    "size": "2–3′",
    "target": "Cut to 6″ in late winter",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light feed in spring",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "",
      "nov": "",
      "dec": ""
    }
  },
  {
    "botanical": "Rosa Iceberg",
    "common": "Iceberg Rose",
    "images": [
      "assets/plants/rosa_iceberg.jpg",
      "assets/plants/rosa_iceberg_1.jpg",
      "assets/plants/rosa_iceberg_2.jpg",
      "assets/plants/rosa_iceberg_3.jpg"
    ],
    "size": "3–4′",
    "target": "Rose - prune hard in winter, deadhead in season",
    "aggression": "Medium",
    "type": "Year-round",
    "fertilize": "Feed in spring and after first bloom",
    "calendar": {
      "jan": "■",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "botanical": "Camellia japonica 'Tomorrow's Pink Wonder'",
    "common": "Tomorrow's Pink Wonder Camellia",
    "images": [
      "assets/plants/camellia_japonica_tomorrows_pink_wonder.jpg"
    ],
    "size": "6–10′",
    "target": "Light shape after bloom",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Acid-loving plant food in spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "△",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": ""
    }
  },
  {
    "botanical": "Camellia japonica 'Debutante'",
    "common": "Debutante Camellia",
    "images": [
      "assets/plants/camellia_japonica_debutante.jpg"
    ],
    "size": "6–8′",
    "target": "Light shape after bloom",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Acid-loving plant food in spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "△",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": ""
    }
  },
  {
    "botanical": "Calamagrostis x acutiflora 'Karl Foerster'",
    "common": "Karl Foerster Feather Reed Grass",
    "images": [
      "assets/plants/calamagrostis_x_acutiflora_karl_foerster.jpg",
      "assets/plants/calamagrostis_x_acutiflora_karl_foerster2.jpg",
      "assets/plants/calamagrostis_x_acutiflora_karl_foerster3.jpg"
    ],
    "size": "4–5′",
    "target": "Cut to 6–12\" in late winter",
    "aggression": "Medium",
    "type": "Cool",
    "fertilize": "Light feed in spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "",
      "aug": "",
      "sep": "△",
      "oct": "△",
      "nov": "",
      "dec": ""
    }
  },
  {
    "botanical": "Westringia fruticosa 'Smokey'",
    "common": "Smokey Coast Rosemary",
    "synonyms": [
      "westringia fruticosa smokey",
      "smokey westringia",
      "smokey coast rosemary"
    ],
    "size": "4–6′",
    "target": "-25–40%",
    "aggression": "Medium",
    "type": "Year",
    "fertilize": "Light fert after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": [
      "assets/plants/westringia_fruticosa_smokey_1.jpg",
      "assets/plants/westringia_fruticosa_smokey_2.jpg",
      "assets/plants/westringia_fruticosa_smokey_3.jpg"
    ]
  },
  {
    "botanical": "Azalea 'Southern Charm'",
    "common": "Southern Charm Azalea",
    "size": "4–6′",
    "target": "Light shape after bloom",
    "aggression": "Light",
    "type": "Shade",
    "fertilize": "Acid fert spring",
    "images": [
      "assets/plants/azalea_southern_charm_1.jpg",
      "assets/plants/azalea_southern_charm_2.jpg",
      "assets/plants/azalea_southern_charm_3.jpg"
    ],
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "botanical": "Dianella 'Tasmanica Variegata'",
    "common": "Variegated Flax Lily",
    "size": "2–3′",
    "target": "Cut to 6–8″ annually",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "images": [
      "assets/plants/dianella_tasmanica_variegata_1.jpg",
      "assets/plants/dianella_tasmanica_variegata_2.jpg",
      "assets/plants/dianella_tasmanica_variegata_3.jpg"
    ],
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "botanical": "Lantana 'Confetti'",
    "common": "Confetti Lantana",
    "size": "2–3′",
    "target": "Cut back 50%",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert spring",
    "images": [
      "assets/plants/lantana_confetti_1.jpg",
      "assets/plants/lantana_confetti_2.jpg",
      "assets/plants/lantana_confetti_3.jpg"
    ],
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    }
  },
  {
    "botanical": "Lantana 'New Gold'",
    "common": "New Gold Lantana",
    "size": "2–3′",
    "target": "Cut back 50%",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert spring",
    "images": [
      "assets/plants/lantana_new_gold_1.jpg",
      "assets/plants/lantana_new_gold_2.jpg",
      "assets/plants/lantana_new_gold_3.jpg"
    ],
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    }
  },
  {
    "botanical": "Leucadendron discolor",
    "common": "Pom Pom Leucadendron",
    "size": "4–6′",
    "target": "Light shape after bloom",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "None or very light",
    "images": [
      "assets/plants/leucadendron_discolor_1.jpg",
      "assets/plants/leucadendron_discolor_2.jpg",
      "assets/plants/leucadendron_discolor_3.jpg"
    ],
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "botanical": "Salvia leucantha 'Daniela's Dream'",
    "common": "Daniela's Dream Salvia",
    "size": "3–4′",
    "target": "Cut to 12–18″ in winter",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "images": [
      "assets/plants/salvia_leucantha_danielas_dream_1.jpg",
      "assets/plants/salvia_leucantha_danielas_dream_2.jpg",
      "assets/plants/salvia_leucantha_danielas_dream_3.jpg"
    ],
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "botanical": "Schefflera arboricola",
    "common": "Schefflera",
    "size": "6–10′",
    "target": "Light shape as needed",
    "aggression": "Light",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "images": [
      "assets/plants/schefflera_arboricola_1.jpg",
      "assets/plants/schefflera_arboricola_2.jpg",
      "assets/plants/schefflera_arboricola_3.jpg"
    ],
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    }
  },
  {
    "botanical": "Tecomaria capensis (Orange)",
    "common": "Cape Honeysuckle",
    "size": "6–10′",
    "target": "-30–50%",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert after prune",
    "images": [
      "assets/plants/tecomaria_capensis_orange_1.jpg",
      "assets/plants/tecomaria_capensis_orange_2.jpg",
      "assets/plants/tecomaria_capensis_orange_3.jpg"
    ],
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    }
  }
];
