// Plant database — 125 plants from CG Pruning Schedule
const PLANTS = [
  {
    "botanical": "Pittosporum",
    "common": "Pittosporum",
    "synonyms": [
      "pitt",
      "pittosporum"
    ],
    "size": "8–15′",
    "target": "-30–50%",
    "aggression": "Med–Heavy",
    "type": "Warm",
    "fertilize": "2–3 wks after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Ligustrum",
    "common": "Privet",
    "synonyms": [
      "privet",
      "wax privet"
    ],
    "size": "10–20′",
    "target": "-40–60%",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "2–3 wks after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Podocarpus",
    "common": "Podocarpus",
    "synonyms": [
      "podocarpus"
    ],
    "size": "10–20′",
    "target": "-30–50%",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "2–3 wks after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Westringia",
    "common": "Coast Rosemary",
    "synonyms": [
      "westringia",
      "rosemary",
      "coast rosemary"
    ],
    "size": "4–8′",
    "target": "-25–40%",
    "aggression": "Medium",
    "type": "Year",
    "fertilize": "Light fert after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": [
      "assets/plants/westringia_2.jpg",
      "assets/plants/westringia_3.jpg",
      "assets/plants/westringia_4.jpg",
      "assets/plants/westringia_5.jpg",
      "assets/plants/westringia_6.jpg",
      "assets/plants/westringia_7.jpg"
    ]
  },
  {
    "botanical": "Roses",
    "common": "Rose",
    "synonyms": [
      "rose",
      "roses",
      "hybrid rose"
    ],
    "size": "3–6′",
    "target": "-20–40%",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "After bloom (light)",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Salvia",
    "common": "Sage",
    "synonyms": [
      "salvia",
      "sage"
    ],
    "size": "2–5′",
    "target": "-20–40%",
    "aggression": "Light–Med",
    "type": "Year",
    "fertilize": "Light fert after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Muhlenbergia",
    "common": "Muhly Grass",
    "synonyms": [
      "muhly",
      "muhlenbergia"
    ],
    "size": "2–4′",
    "target": "Cut to 2–6\"",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Lomandra",
    "common": "Mat Rush",
    "synonyms": [
      "lomandra",
      "mat rush"
    ],
    "size": "2–4′",
    "target": "Cut to 4–8\"",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Ceanothus",
    "common": "California Lilac",
    "synonyms": [
      "ceanothus",
      "california lilac",
      "wild lilac"
    ],
    "size": "3–8′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Cool",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Muhlenbergia rigens",
    "common": "Deer Grass",
    "synonyms": [],
    "size": "3–5′",
    "target": "Cut to 6–12\"",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "Spring fert",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Pennisetum setaceum",
    "common": "Fountain Grass",
    "synonyms": [],
    "size": "3–4′",
    "target": "Cut to 4–6\"",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "Spring fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    },
    "images": [
      "assets/plants/pennisetum_setaceum_2.jpg",
      "assets/plants/pennisetum_setaceum_3.jpg",
      "assets/plants/pennisetum_setaceum_4.jpg",
      "assets/plants/pennisetum_setaceum_5.jpg",
      "assets/plants/pennisetum_setaceum_6.jpg",
      "assets/plants/pennisetum_setaceum_7.jpg",
      "assets/plants/pennisetum_setaceum_8.jpg"
    ]
  },
  {
    "botanical": "Nassella tenuissima",
    "common": "Mexican Feather Grass",
    "synonyms": [],
    "size": "1–2′",
    "target": "Cut to 3–4\"",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Festuca glauca",
    "common": "Blue Fescue",
    "synonyms": [],
    "size": "1–2′",
    "target": "Cut to 2–3\"",
    "aggression": "Medium",
    "type": "Cool",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Lomandra longifolia 'Breeze'",
    "common": "Breeze Mat Rush",
    "synonyms": [
      "lomandra breeze",
      "breeze"
    ],
    "size": "2–3′",
    "target": "Cut to 4–6\"",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/lomandra_longifolia_breeze.jpg"
    ]
  },
  {
    "botanical": "Dietes iridioides",
    "common": "Fortnight Lily",
    "synonyms": [],
    "size": "2–3′",
    "target": "Cut to 6\"",
    "aggression": "Medium",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "△",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Arctostaphylos 'Emerald Carpet'",
    "common": "Emerald Carpet Manzanita",
    "synonyms": [
      "emerald carpet",
      "manzanita"
    ],
    "size": "1–2′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Cool",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Carex pensylvanica",
    "common": "PA Sedge",
    "synonyms": [],
    "size": "1–2′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Shade",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "△",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Myoporum parvifolium",
    "common": "Myoporum",
    "synonyms": [
      "myoporum",
      "prostrate myoporum"
    ],
    "size": "6–12\"",
    "target": "Cut to 2–4\"",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Senecio mandraliscae",
    "common": "Blue Senecio",
    "synonyms": [],
    "size": "1–2′",
    "target": "Cut to 2–4\"",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "△",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Drosanthemum hispidum",
    "common": "Drosanthemum",
    "synonyms": [
      "drosanthemum",
      "rose carpet"
    ],
    "size": "4–8\"",
    "target": "Cut to 2–3\"",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "△",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Erigeron karvinskianus",
    "common": "Santa Barbara Daisy",
    "synonyms": [],
    "size": "1–2′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Gazania rigens",
    "common": "Gazania",
    "synonyms": [
      "gazania",
      "treasure flower"
    ],
    "size": "6–12\"",
    "target": "Cut to 4–6\"",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "△",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Lantana camera",
    "common": "Lantana",
    "synonyms": [],
    "size": "3–5′",
    "target": "-30–50%",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "Spring fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "△",
      "nov": "",
      "dec": ""
    },
    "images": []
  },
  {
    "botanical": "Salvia leucantha",
    "common": "Mexican Bush Sage",
    "synonyms": [],
    "size": "3–4′",
    "target": "Cut to 6–12\"",
    "aggression": "Heavy",
    "type": "Warm",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "△",
      "nov": "△",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Nepeta 'Walker's Low'",
    "common": "Walker's Low Catmint",
    "synonyms": [
      "walkers low",
      "catmint",
      "catnip"
    ],
    "size": "2–3′",
    "target": "Cut to 4–6\"",
    "aggression": "Medium",
    "type": "Year",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "△",
      "oct": "",
      "nov": "",
      "dec": ""
    },
    "images": []
  },
  {
    "botanical": "Lavandula angustifolia 'Hidcote'",
    "common": "Lavender",
    "synonyms": [],
    "size": "2–3′",
    "target": "Cut to 6–8\"",
    "aggression": "Medium",
    "type": "Cool",
    "fertilize": "Light after bloom",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Heuchera maxima",
    "common": "Coral Bells",
    "synonyms": [],
    "size": "1–2′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Shade",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "△",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Rosa hybrids",
    "common": "Shrub Roses",
    "synonyms": [],
    "size": "3–5′",
    "target": "-20–40%",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "After bloom",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Olea europaea 'Little Ollie'",
    "common": "Little Ollie Olive",
    "synonyms": [
      "little ollie",
      "dwarf olive"
    ],
    "size": "6–8′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "△",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Trachelospermum jasminoides",
    "common": "Star Jasmine",
    "synonyms": [],
    "size": "10–15′",
    "target": "-20–30%",
    "aggression": "Light–Med",
    "type": "Year",
    "fertilize": "Light fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "△",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": [
      "assets/plants/trachelospermum_jasminoides.jpg"
    ]
  },
  {
    "botanical": "Viburnum davidii",
    "common": "David Viburnum",
    "synonyms": [
      "david viburnum",
      "viburnum"
    ],
    "size": "3–4′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "△",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Photinia × fraseri",
    "common": "Fraser Photinia",
    "synonyms": [],
    "size": "8–15′",
    "target": "-30–40%",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Spring fert",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Buxus 'Green Beauty'",
    "common": "Green Beauty Boxwood",
    "synonyms": [
      "green beauty boxwood",
      "boxwood"
    ],
    "size": "3–5′",
    "target": "-20–30%",
    "aggression": "Light–Med",
    "type": "Year",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Heteromeles arbutifolia",
    "common": "Toyon",
    "synonyms": [],
    "size": "8–15′",
    "target": "-20–30%",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "△",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "△",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Quercus agrifolia",
    "common": "Coast Live Oak",
    "synonyms": [],
    "size": "15–30′",
    "target": "",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Arbutus 'Marina'",
    "common": "Marina Strawberry Tree",
    "synonyms": [],
    "size": "15–30′",
    "target": "",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Prunus ilicifolia ssp. lyonii",
    "common": "Catalina Cherry",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Chilopsis linearis",
    "common": "Desert Willow",
    "synonyms": [],
    "size": "15–30′",
    "target": "",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "x Chitalpa tashkentensis 'Pink Dawn'",
    "common": "Pink Chitalpa",
    "synonyms": [],
    "size": "15–30′",
    "target": "",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Cercis occidentalis",
    "common": "Western Redbud",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Aesculus californica",
    "common": "California Buckeye",
    "synonyms": [],
    "size": "15–30′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Year",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Juglans californica var. californica",
    "common": "Southern California Black Walnut",
    "synonyms": [],
    "size": "15–30′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Year",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Artemisia californica",
    "common": "California Sagebrush",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Artemisia californica 'Canyon Gray'",
    "common": "Canyon Gray Sagebrush",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Artemisia californica 'Montara'",
    "common": "Montara Sagebrush",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Rhus ovata",
    "common": "Sugar Bush",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Rhus integrifolia",
    "common": "Lemonade Berry",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Prunus ilicifolia ssp. ilicifolia",
    "common": "Hollyleaf Cherry",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Rhamnus californica",
    "common": "Coffeeberry",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Calliandra californica",
    "common": "Baja Fairy Duster",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Isomeris arborea",
    "common": "Bladderpod",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Eriogonum fasciculatum",
    "common": "California Buckwheat",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Eriogonum cinereum",
    "common": "Ashyleaf Buckwheat",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Eriogonum arborescens",
    "common": "Santa Cruz Island Buckwheat",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Eriogonum fasciculatum 'Theodore Payne'",
    "common": "Theodore Payne Buckwheat",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Baccharis pilularis 'Pigeon Point'",
    "common": "Pigeon Point Coyote Brush",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Lepechinia fragrans",
    "common": "Fragrant Pitcher Sage",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Abutilon palmeri",
    "common": "Palmer's Indian Mallow",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Sphaeralcea ambigua",
    "common": "Desert Mallow / Apricot Mallow",
    "synonyms": [],
    "size": "1–3′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Eriogonum grande var. rubescens",
    "common": "Red Buckwheat",
    "synonyms": [],
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Achillea millefolium",
    "common": "Common Yarrow",
    "synonyms": [],
    "size": "1–3′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Asclepias fascicularis",
    "common": "Narrow Leaf Milkweed",
    "synonyms": [],
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Asclepias speciosa",
    "common": "Showy Milkweed",
    "synonyms": [],
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Anemopsis californica",
    "common": "Yerba Mansa",
    "synonyms": [],
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Iris douglasiana",
    "common": "Douglas Iris",
    "synonyms": [],
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Bouteloua gracilis",
    "common": "Blue Grama",
    "synonyms": [],
    "size": "2–4′",
    "target": "",
    "aggression": "Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    },
    "images": [
      "assets/plants/bouteloua_gracilis_2.jpg",
      "assets/plants/bouteloua_gracilis_3.jpg",
      "assets/plants/bouteloua_gracilis_4.jpg"
    ]
  },
  {
    "botanical": "Leymus condensatus 'Canyon Prince'",
    "common": "Canyon Prince Wild Rye",
    "synonyms": [],
    "size": "2–4′",
    "target": "",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Carex tumulicola",
    "common": "Foothill Sedge / Berkeley Sedge",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Carex pansa",
    "common": "Sand Dune Sedge",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Carex barbarae",
    "common": "Valley Sedge",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Sesleria autumnalis",
    "common": "Sesleria Autumnalis",
    "synonyms": [],
    "size": "2–4′",
    "target": "",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Berberis aquifolium var. repens",
    "common": "Creeping Barberry / Creeping Oregon Grape",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Erigeron glaucus",
    "common": "Seaside Daisy",
    "synonyms": [],
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Hesperaloe parviflora",
    "common": "Red Yucca",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Agave attenuata 'Boutin Blue'",
    "common": "Blue Fox Tail Agave",
    "synonyms": [],
    "size": "1–4′",
    "target": "",
    "aggression": "Light",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": ""
    },
    "images": []
  },
  {
    "botanical": "Agave attenuata",
    "common": "Fox Tail Agave",
    "synonyms": [],
    "size": "1–4′",
    "target": "",
    "aggression": "Light",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": ""
    },
    "images": []
  },
  {
    "botanical": "Agave 'Blue Flame'",
    "common": "Blue Flame Agave",
    "synonyms": [],
    "size": "1–4′",
    "target": "",
    "aggression": "Light",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": ""
    },
    "images": []
  },
  {
    "botanical": "Aloe vera",
    "common": "Aloe Vera",
    "synonyms": [],
    "size": "1–4′",
    "target": "",
    "aggression": "Light",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": ""
    },
    "images": []
  },
  {
    "botanical": "Aloe 'Blue Elf'",
    "common": "Blue Elf Aloe",
    "synonyms": [],
    "size": "1–4′",
    "target": "",
    "aggression": "Light",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "",
      "feb": "",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": ""
    },
    "images": []
  },
  {
    "botanical": "Rosmarinus officinalis",
    "common": "Rosemary",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Bougainvillea spectabilis",
    "common": "Bougainvillea",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/bougainvillea_spectabilis_4.jpg"
    ]
  },
  {
    "botanical": "Olea europaea",
    "common": "Olive Tree",
    "synonyms": [],
    "size": "15–30′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Year",
    "fertilize": "Light spring fert",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Cupressus sempervirens",
    "common": "Italian Cypress",
    "synonyms": [],
    "size": "15–30′",
    "target": "",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "",
      "jul": "",
      "aug": "",
      "sep": "",
      "oct": "",
      "nov": "△",
      "dec": "△"
    },
    "images": []
  },
  {
    "botanical": "Juniperus chinensis 'Torulosa'",
    "common": "Juniper",
    "synonyms": [],
    "size": "",
    "target": "",
    "aggression": "Light–Med",
    "type": "Warm",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Rhaphiolepis indica",
    "common": "Indian Hawthorn",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Carissa macrocarpa",
    "common": "Natal Plum",
    "synonyms": [],
    "size": "3–8′",
    "target": "",
    "aggression": "Light–Med",
    "type": "Shade",
    "fertilize": "Minimal",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/carissa_green_carpet.jpg",
      "assets/plants/carissa_macrocarpa_booxwood_beauty.jpg"
    ]
  },
  {
    "botanical": "Phormium tenax",
    "common": "New Zealand Flax",
    "synonyms": [],
    "size": "1–3′",
    "target": "",
    "aggression": "Med–Heavy",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": []
  },
  {
    "botanical": "Achillea millefolium 'Pomegranate'",
    "common": "Pomegranate Yarrow",
    "synonyms": [],
    "size": "2′",
    "target": "Cut to 6–8″",
    "aggression": "Medium",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/achillea_millefolium_pomegranate.jpg"
    ]
  },
  {
    "botanical": "Azalea 'Orange Delight'",
    "common": "Orange Delight Azalea",
    "synonyms": [],
    "size": "3–5′",
    "target": "Light shape after bloom",
    "aggression": "Light",
    "type": "Shade",
    "fertilize": "Acid fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/azalea_orange_delight.jpg"
    ]
  },
  {
    "botanical": "Hydrangea macrophylla 'Nikko Blue'",
    "common": "Nikko Blue Hydrangea",
    "synonyms": [],
    "size": "4–6′",
    "target": "Deadhead + light trim",
    "aggression": "Light",
    "type": "Shade",
    "fertilize": "Rich fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/hydrangea_macrophylla_nikko_blue.jpg"
    ]
  },
  {
    "botanical": "Hydrangea macrophylla 'Leuchtfeuer'",
    "common": "Leuchtfeuer Hydrangea",
    "synonyms": [],
    "size": "4–6′",
    "target": "Deadhead + light trim",
    "aggression": "Light",
    "type": "Shade",
    "fertilize": "Rich fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/hydrangea_macrophylla_leuchtfeuer.jpg"
    ]
  },
  {
    "botanical": "Xylosma congestum",
    "common": "Xylosma",
    "synonyms": [],
    "size": "8–15′",
    "target": "-20–40%",
    "aggression": "Medium",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/xylosma_congestum.jpg"
    ]
  },
  {
    "botanical": "Asparagus densiflorus 'Myers'",
    "common": "Myers Asparagus Fern",
    "synonyms": [],
    "size": "2–3′",
    "target": "Clean up dead fronds",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/asparagus_densiflorus_myers.jpg"
    ]
  },
  {
    "botanical": "Philodendron 'Xanadu'",
    "common": "Xanadu Philodendron",
    "synonyms": [],
    "size": "3–5′",
    "target": "Remove damaged leaves",
    "aggression": "Light",
    "type": "Shade",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/philodendron_xanadu.jpg"
    ]
  },
  {
    "botanical": "Limonium perezii",
    "common": "Sea Lavender",
    "synonyms": [],
    "size": "2–3′",
    "target": "Cut back after bloom",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/limonium_perezii.jpg"
    ]
  },
  {
    "botanical": "Dietes",
    "common": "Dietes",
    "synonyms": [],
    "size": "2–3′",
    "target": "Cut to 6–8″ annually",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/dietes.jpg"
    ]
  },
  {
    "botanical": "Lavandula dentata",
    "common": "French Lavender",
    "synonyms": [],
    "size": "2–3′",
    "target": "Trim after bloom",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert after trim",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/lavandula_dentata.jpg"
    ]
  },
  {
    "botanical": "Lavandula ginginsii 'Goodwin Creek Grey'",
    "common": "Goodwin Creek Grey Lavender",
    "synonyms": [],
    "size": "2–3′",
    "target": "Trim after bloom",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert after trim",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/lavandula_ginginsii_goodwin_creek_grey.jpg"
    ]
  },
  {
    "botanical": "Tulbaghia violacea",
    "common": "Society Garlic",
    "synonyms": [],
    "size": "1–2′",
    "target": "Cut back after bloom",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/tulbaghia_violacea.jpg"
    ]
  },
  {
    "botanical": "Phlomis fruticosa",
    "common": "Jerusalem Sage",
    "synonyms": [],
    "size": "3–4′",
    "target": "Cut back after bloom",
    "aggression": "Medium",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/phlomis_fruticosa.jpg"
    ]
  },
  {
    "botanical": "Achillea 'Moonshine' Yellow",
    "common": "Moonshine Yarrow",
    "synonyms": [],
    "size": "2′",
    "target": "Cut to 6–8″",
    "aggression": "Medium",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/achillea_moonshine_yellow.jpg"
    ]
  },
  {
    "botanical": "Lantana 'New Gold'",
    "common": "New Gold Lantana",
    "synonyms": [],
    "size": "2–3′",
    "target": "Cut back 50%",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": [
      "assets/plants/lanatana_new_gold.jpg"
    ]
  },
  {
    "botanical": "Lantana 'Confetti'",
    "common": "Confetti Lantana",
    "synonyms": [],
    "size": "2–3′",
    "target": "Cut back 50%",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": [
      "assets/plants/lanatana_confetti.jpg"
    ]
  },
  {
    "botanical": "Azalea 'Southern Charm' (Pink)",
    "common": "Southern Charm Azalea",
    "synonyms": [],
    "size": "4–6′",
    "target": "Light shape after bloom",
    "aggression": "Light",
    "type": "Shade",
    "fertilize": "Acid fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/azalea_southern_charm_pink.jpg"
    ]
  },
  {
    "botanical": "Azalea 'Red Bird'",
    "common": "Red Bird Azalea",
    "synonyms": [],
    "size": "3–4′",
    "target": "Light shape after bloom",
    "aggression": "Light",
    "type": "Shade",
    "fertilize": "Acid fert spring",
    "calendar": {
      "jan": "△",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "△",
      "jul": "△",
      "aug": "△",
      "sep": "△",
      "oct": "△",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/azalea_red_bird.jpg"
    ]
  },
  {
    "botanical": "Lomandra longifolia 'Platinum Beauty'ï",
    "common": "Platinum Beauty Lomandra",
    "synonyms": [],
    "size": "3–4′",
    "target": "Cut to 4–6″ annually",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/lomandra_longifolia_platinum_beauty.jpg"
    ]
  },
  {
    "botanical": "Strelitzia nicolai",
    "common": "White Bird of Paradise",
    "synonyms": [],
    "size": "15–25′",
    "target": "Remove dead leaves",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/strelitzia_nocolao.jpg"
    ]
  },
  {
    "botanical": "Tecomaria capensis (Orange)",
    "common": "Cape Honeysuckle",
    "synonyms": [],
    "size": "6–10′",
    "target": "-30–50%",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": [
      "assets/plants/tecomaria_capensis_orange.jpg"
    ]
  },
  {
    "botanical": "Strelitzia reginae",
    "common": "Bird of Paradise",
    "synonyms": [],
    "size": "4–6′",
    "target": "Remove dead leaves/seed heads",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/strelitzia_regimae.jpg"
    ]
  },
  {
    "botanical": "Tacoma orange Jubliee",
    "common": "Orange Jubilee",
    "synonyms": [],
    "size": "8–12′",
    "target": "-30–50%",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert after prune",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": [
      "assets/plants/tacoma_orange_jubliee.jpg"
    ]
  },
  {
    "botanical": "Lantana montevidensis (Purple)",
    "common": "Purple Lantana",
    "synonyms": [],
    "size": "2–3′",
    "target": "Cut back 50%",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": [
      "assets/plants/lantana_montevidensis_purple.jpg"
    ]
  },
  {
    "botanical": "Salvia 'Allen Chickering'",
    "common": "Allen Chickering Salvia",
    "synonyms": [],
    "size": "3–4′",
    "target": "Cut back after bloom",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": [
      "assets/plants/salvia_allen_chickering.jpg"
    ]
  },
  {
    "botanical": "Salvia leucantha 'Santa Barbara'",
    "common": "Santa Barbara Mexican Sage",
    "synonyms": [],
    "size": "3–4′",
    "target": "Cut to 12–18″ in winter",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/salvia_leucantha_santa_barbara.jpg"
    ]
  },
  {
    "botanical": "Salvia leucantha 'Daniela's Dream'",
    "common": "Daniela's Dream Salvia",
    "synonyms": [],
    "size": "3–4′",
    "target": "Cut to 12–18″ in winter",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/salvia_leucantha_danielles_dream.jpg"
    ]
  },
  {
    "botanical": "Salvia 'Mystic Spires'",
    "common": "Mystic Spires Salvia",
    "synonyms": [],
    "size": "2–3′",
    "target": "Cut back after bloom",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": [
      "assets/plants/salvia_mystic_spires.jpg"
    ]
  },
  {
    "botanical": "Bougainvillea 'La jolla'",
    "common": "La Jolla Bougainvillea",
    "synonyms": [],
    "size": "6–8′",
    "target": "Trim as needed",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": [
      "assets/plants/bougainvillea_la_jolla.jpg"
    ]
  },
  {
    "botanical": "Cordyline 'Lime Passion'",
    "common": "Lime Passion Cordyline",
    "synonyms": [],
    "size": "3–5′",
    "target": "Remove dead leaves",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/cordyline_lime_passion.jpg",
      "assets/plants/cordyline_lime_passion_2.jpg"
    ]
  },
  {
    "botanical": "Bougainvillea 'Barbara Karst'",
    "common": "Barbara Karst Bougainvillea",
    "synonyms": [],
    "size": "6–10′",
    "target": "Trim as needed",
    "aggression": "Medium",
    "type": "Warm",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "△",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "△",
      "aug": "",
      "sep": "",
      "oct": "△",
      "nov": "■",
      "dec": "△"
    },
    "images": [
      "assets/plants/bougainvillea_barbara_karst.jpg"
    ]
  },
  {
    "botanical": "Leucadendron discolor 'pom pom'",
    "common": "Pom Pom Leucadendron",
    "synonyms": [],
    "size": "4–6′",
    "target": "Light shape after bloom",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "None or very light",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/leucadendron_discolor_pom_pom.jpg"
    ]
  },
  {
    "botanical": "Cordyline 'Design-a-line'",
    "common": "Design-a-Line Cordyline",
    "synonyms": [],
    "size": "3–4′",
    "target": "Remove dead leaves",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/cordyline_design_a_line.jpg",
      "assets/plants/cordyline_design_a_line_2.jpg"
    ]
  },
  {
    "botanical": "Dianella 'Tesmanica Variegata'",
    "common": "Variegated Flax Lily",
    "synonyms": [],
    "size": "2–3′",
    "target": "Cut to 6–8″ annually",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/dianella_tesmanica_variegata.jpg"
    ]
  },
  {
    "botanical": "Dianella revoluta 'Little Rev'",
    "common": "Little Rev Dianella",
    "synonyms": [],
    "size": "1–2′",
    "target": "Cut to 6–8″ annually",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert after cut",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/dianella_revoluta_little_rev.jpg"
    ]
  },
  {
    "botanical": "Pennisetum 'Massalsium' 'Red Bunny'",
    "common": "Red Bunny Fountain Grass",
    "synonyms": [],
    "size": "3–4′",
    "target": "Cut to 6–8″ in late winter",
    "aggression": "Heavy",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/pennisetum_massalcum_red_bunny.jpg"
    ]
  },
  {
    "botanical": "Agapanthus 'Tinkerbell'",
    "common": "Tinkerbell Lily of the Nile",
    "synonyms": [],
    "size": "1–2′",
    "target": "Remove dead stalks after bloom",
    "aggression": "Light",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/agapanthus_tinkerbell.jpg"
    ]
  },
  {
    "botanical": "Hemerocallis 'stella d orro'",
    "common": "Stella de Oro Daylily",
    "synonyms": [],
    "size": "1–2′",
    "target": "Cut back in late winter",
    "aggression": "Medium",
    "type": "Year",
    "fertilize": "Light fert spring",
    "calendar": {
      "jan": "",
      "feb": "■",
      "mar": "■",
      "apr": "■",
      "may": "■",
      "jun": "■",
      "jul": "■",
      "aug": "■",
      "sep": "■",
      "oct": "■",
      "nov": "■",
      "dec": "■"
    },
    "images": [
      "assets/plants/hemercocallis_stella_d_orro.jpg"
    ]
  }
];
